from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot threshold tradeoff chart")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("results/threshold_tradeoff/summary.json"),
        help="Input JSON generated by benchmark_threshold_tradeoff.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/threshold_tradeoff/threshold_tradeoff.png"),
        help="Output chart path",
    )
    return parser.parse_args()


def mb(bytes_value: int) -> float:
    return bytes_value / (1024 * 1024)


def main() -> None:
    args = parse_args()
    with args.input.open("r", encoding="utf-8") as f:
        report = json.load(f)

    thresholds = [float(x) for x in report["thresholds"]]
    target_fpr = float(report["target_fpr"])
    feature_grid = [int(x) for x in report["n_features"]]
    results = report["results"]

    plt.style.use("dark_background")
    fig, axes = plt.subplots(1, 2, figsize=(16, 7), constrained_layout=False)
    fig.patch.set_facecolor("#08142A")
    for ax in axes:
        ax.set_facecolor("#0A1735")

    colors = ["#4FC3F7", "#6FF0C3", "#FFD54A", "#FF5B5B"]
    labels = [f"n={n}" for n in feature_grid]
    x = np.arange(len(thresholds))

    left = axes[0]
    for idx, n_features in enumerate(feature_grid):
        series = results[str(n_features)]
        system_fprs = [float(row["system_fpr"]) for row in series]
        left.plot(
            thresholds,
            system_fprs,
            marker="o",
            linewidth=2.4,
            markersize=5,
            color=colors[idx % len(colors)],
            label=labels[idx],
        )

    left.axhline(target_fpr, color="#FF6B6B", linestyle="--", linewidth=1.4, label=f"Target FPR = {target_fpr:g}")
    left.set_title(f"Threshold vs System FPR\n(C++ Trigram, Target FPR = {target_fpr:g})", fontsize=14, fontweight="bold")
    left.set_xlabel("Classification Threshold", fontsize=11)
    left.set_ylabel("System FPR", fontsize=11)
    left.set_xticks(thresholds)
    left.set_ylim(bottom=0)
    left.grid(True, linestyle="--", alpha=0.15)
    left.legend(framealpha=0.22, fontsize=9)

    right = axes[1]
    for idx, n_features in enumerate(feature_grid):
        series = results[str(n_features)]
        backup_counts = [int(row["backup_fn_count"]) for row in series]
        right.plot(
            thresholds,
            backup_counts,
            marker="o",
            linewidth=2.4,
            markersize=5,
            color=colors[idx % len(colors)],
            label=labels[idx],
        )

    right.set_title(f"Threshold vs Backup BF Size\n(C++ Trigram, Target FPR = {target_fpr:g})", fontsize=14, fontweight="bold")
    right.set_xlabel("Classification Threshold", fontsize=11)
    right.set_ylabel("Training FN Count (backup BF size)", fontsize=11)
    right.set_xticks(thresholds)
    right.grid(True, linestyle="--", alpha=0.15)
    right.legend(framealpha=0.22, fontsize=9)

    fig.suptitle(
        "Threshold Tradeoff - Lower FPR Requires Higher Threshold -> Larger Backup BF",
        fontsize=16,
        fontweight="bold",
        y=0.98,
    )
    fig.text(
        0.5,
        0.02,
        "Higher threshold pushes more good URLs into the backup BF, increasing memory cost",
        ha="center",
        va="bottom",
        fontsize=10,
        color="#9AB0D0",
    )
    fig.tight_layout(rect=[0, 0.05, 1, 0.95])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output, dpi=220)
    print(f"Wrote threshold tradeoff chart to: {args.output}")


if __name__ == "__main__":
    main()
