from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot threshold tradeoff chart")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("results/threshold_tradeoff/summary.json"),
        help="Input JSON generated by benchmark_threshold_tradeoff.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/threshold_tradeoff/threshold_tradeoff.png"),
        help="Output chart path",
    )
    return parser.parse_args()


def mb(bytes_value: int) -> float:
    return bytes_value / (1024 * 1024)


def main() -> None:
    args = parse_args()

    with args.input.open("r", encoding="utf-8") as f:
        report = json.load(f)

    thresholds = [float(x) for x in report["thresholds"]]
    target_fprs = [float(x) for x in report["target_fprs"]]
    feature_grid = [int(x) for x in report["n_features"]]

    plt.style.use("default")

    fig, axes = plt.subplots(
        2,
        len(target_fprs),
        figsize=(8 * len(target_fprs), 10),
        constrained_layout=False,
    )

    fig.patch.set_facecolor("white")

    for row in axes:
        for ax in row:
            ax.set_facecolor("white")

    colors = [
        "#4C72B0",
        "#55A868",
        "#C44E52",
        "#8172B2",
    ]

    labels = [f"n={n}" for n in feature_grid]

    # --------------------------------------------------------
    # Top row : System FPR
    # --------------------------------------------------------

    for col, target_fpr in enumerate(target_fprs):

        results = report["results_by_target_fpr"][str(target_fpr)]

        left = axes[0][col]

        for idx, n_features in enumerate(feature_grid):

            series = results[str(n_features)]

            system_fprs = [
                float(row["system_fpr"])
                for row in series
            ]

            left.plot(
                thresholds,
                system_fprs,
                marker="o",
                linewidth=2.5,
                markersize=6,
                color=colors[idx % len(colors)],
                label=labels[idx],
            )

        left.axhline(
            target_fpr,
            color="black",
            linestyle="--",
            linewidth=1.5,
            label=f"Target = {target_fpr:g}",
        )

        left.set_title(
            f"System False Positive Rate\n(Target FPR = {target_fpr:g})",
            fontsize=13,
            fontweight="bold",
        )

        left.set_xlabel("Classification Threshold")
        left.set_ylabel("System False Positive Rate")

        left.set_xticks(thresholds)
        left.set_ylim(bottom=0)

        left.grid(
            True,
            linestyle="--",
            alpha=0.30,
        )

        left.legend(fontsize=9)

    # --------------------------------------------------------
    # Bottom row : Backup BF
    # --------------------------------------------------------

    for col, target_fpr in enumerate(target_fprs):

        results = report["results_by_target_fpr"][str(target_fpr)]

        right = axes[1][col]

        for idx, n_features in enumerate(feature_grid):

            series = results[str(n_features)]

            backup_counts = [
                int(row["backup_fn_count"])
                for row in series
            ]

            right.plot(
                thresholds,
                backup_counts,
                marker="o",
                linewidth=2.5,
                markersize=6,
                color=colors[idx % len(colors)],
                label=labels[idx],
            )

        right.set_title(
            f"Backup Bloom Filter Size\n(Target FPR = {target_fpr:g})",
            fontsize=13,
            fontweight="bold",
        )

        right.set_xlabel("Classification Threshold")
        right.set_ylabel("Backup Bloom Filter Entries")

        right.set_xticks(thresholds)

        right.grid(
            True,
            linestyle="--",
            alpha=0.30,
        )

        right.legend(fontsize=9)

    fig.suptitle(
        "Threshold Trade-off Analysis Across Target False Positive Rates",
        fontsize=18,
        fontweight="bold",
    )

    fig.text(
        0.5,
        0.02,
        "Increasing the classification threshold reduces system false positive rate but increases the size of the backup Bloom Filter.",
        ha="center",
        fontsize=10,
        color="dimgray",
    )

    fig.tight_layout(rect=[0, 0.05, 1, 0.96])

    args.output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.savefig(
        args.output,
        dpi=300,
        bbox_inches="tight",
    )

    print(f"Wrote threshold tradeoff chart to: {args.output}")


if __name__ == "__main__":
    main() 