from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot memory usage variants vs standard Bloom filter"
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("results/memory_usage_variants/summary.json"),
        help="Path to summary JSON generated by benchmark_memory_variants.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/memory_usage_variants/memory_usage_variants.png"),
        help="Output chart path",
    )
    return parser.parse_args()


def mb_from_bytes(num_bytes: int) -> float:
    return num_bytes / (1024 * 1024)


def main() -> None:
    args = parse_args()

    with args.input.open("r", encoding="utf-8") as f:
        summary = json.load(f)

    target_fprs = [float(x) for x in summary["target_fprs"]]
    results = summary["results_by_target_fpr"]

    variant_order = [
        ("cpp_trigram", "C++ Trigram", "#4C72B0"),
        ("char_trigram_python", "Char Trigram (Python)", "#55A868"),
        ("word_default_python", "Word Default (Python)", "#C44E52"),
    ]

    standard_mb = [
        mb_from_bytes(results[str(t)]["standard_bloom"]["memory_bytes"])
        for t in target_fprs
    ]

    variant_mb = {
        key: [
            mb_from_bytes(
                results[str(t)]["best_variants"][key]["total_memory_bytes"]
            )
            for t in target_fprs
        ]
        for key, _, _ in variant_order
    }

    reductions = {
        key: [
            results[str(t)]["best_variants"][key]["memory_reduction_percent"]
            for t in target_fprs
        ]
        for key, _, _ in variant_order
    }

    plt.style.use("default")

    fig, ax = plt.subplots(figsize=(12.8, 6.6))

    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")

    x = np.arange(len(target_fprs))
    width = 0.22

    for idx, (key, label, color) in enumerate(variant_order):

        offset = (idx - 1) * width

        bars = ax.bar(
            x + offset,
            variant_mb[key],
            width=width,
            color=color,
            label=label,
        )

        for bar, red in zip(bars, reductions[key]):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.002,
                f"{red:.0f}%",
                ha="center",
                va="bottom",
                fontsize=9,
                fontweight="bold",
            )

    ax.plot(
        x,
        standard_mb,
        color="black",
        marker="o",
        linestyle="--",
        linewidth=2.2,
        label="Standard Bloom Filter",
    )

    labels = [f"Target FPR\n{t:g}" for t in target_fprs]

    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=11)

    ax.set_ylabel("Memory (MB)", fontsize=12)

    ax.set_title(
        "Memory Usage Comparison Across Learned Bloom Filter Variants",
        fontsize=17,
        fontweight="bold",
        pad=12,
    )

    ax.grid(
        axis="y",
        linestyle="--",
        alpha=0.30,
    )

    ax.set_axisbelow(True)

    ax.legend(
        loc="upper right",
        fontsize=10,
    )

    fig.text(
        0.5,
        0.02,
        "Percentage labels indicate memory reduction relative to the Standard Bloom Filter.",
        ha="center",
        fontsize=10,
        color="dimgray",
    )

    fig.tight_layout(rect=[0, 0.05, 1, 0.96])

    args.output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.savefig(
        args.output,
        dpi=300,
        bbox_inches="tight",
    )

    print(f"Wrote memory usage chart to: {args.output}")


if __name__ == "__main__":
    main() 